In [1]:
from sklearnex import patch_sklearn
patch_sklearn()

Extension for Scikit-learn* enabled (https://github.com/uxlfoundation/scikit-learn-intelex)

In [2]:
import pandas as pd 
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.metrics import accuracy_score
from sklearn.compose import make_column_selector,make_column_transformer
from sklearn.pipeline import Pipeline
import numpy as np
from tqdm import tqdm
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv("F:\MACHINE LEARNING\SessionsMaterial\Cases\student_performance\student_dataset_10000_rows.csv")
X,y=df.drop('placement_status',axis=1),df.placement_status
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.3,random_state=26,stratify=y)

In [4]:
svm = SVC(kernel='linear')
svm.fit(X_train, y_train)
pred = svm.predict(X_test)
accuracy_score(y_test, pred)

0.9993333333333333

In [5]:
df=pd.read_csv("F:\MACHINE LEARNING\SessionsMaterial\Cases\human-resources-analytics\HR_comma_sep.csv")
X,y=df.drop('left',axis=1),df.left
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.3,random_state=26)

In [6]:
ohe=OneHotEncoder(sparse_output=False).set_output(transform='pandas')
sc=StandardScaler().set_output(transform='pandas')
ct=make_column_transformer((ohe,make_column_selector(dtype_include=object)),('passthrough',make_column_selector(dtype_exclude=object)),verbose_feature_names_out=False)
svm = SVC(kernel='linear')
pipe=Pipeline([('ct',ct),('sc',sc),('svm',svm)])
pipe.fit(X_train, y_train)
pred = pipe.predict(X_test)
accuracy_score(y_test, pred)

0.7757279395421205

In [7]:
ohe=OneHotEncoder(sparse_output=False).set_output(transform='pandas')
sc=StandardScaler().set_output(transform='pandas')
ct=make_column_transformer((ohe,make_column_selector(dtype_include=object)),('passthrough',make_column_selector(dtype_exclude=object)),verbose_feature_names_out=False)
cs=np.linspace(.001,10,20)
scores=[]
for c in tqdm(cs):
    svm = SVC(kernel='linear',C=c)
    pipe=Pipeline([('ct',ct),('sc',sc),('svm',svm)])
    pipe.fit(X_train, y_train)
    pred = pipe.predict(X_test)
    scores.append([c,accuracy_score(y_test, pred)])

df_score=pd.DataFrame(scores,columns=['C','scores'])
df_score.sort_values('scores',ascending=False,ignore_index=True)[:20]

100%|██████████| 20/20 [01:51<00:00,  5.59s/it]

            C    scores
0    0.527263  0.775728
1    1.053526  0.775728
2    1.579789  0.775728
3    2.106053  0.775728
4    6.316158  0.775728
5    2.632316  0.775728
6    3.158579  0.775728
7    3.684842  0.775728
8    4.211105  0.775728
9    4.737368  0.775728
10   5.263632  0.775728
11   5.789895  0.775728
12   8.421211  0.775728
13   6.842421  0.775728
14   7.368684  0.775728
15   7.894947  0.775728
16   9.473737  0.775728
17   8.947474  0.775728
18  10.000000  0.775728
19   0.001000  0.763503

In [8]:
svm = SVC(kernel='poly')
pipe=Pipeline([('ct',ct),('sc',sc),('svm',svm)])
pipe.fit(X_train, y_train)
pred = pipe.predict(X_test)
accuracy_score(y_test, pred)

0.9339853300733496

In [9]:
ohe=OneHotEncoder(sparse_output=False).set_output(transform='pandas')
sc=StandardScaler().set_output(transform='pandas')
ct=make_column_transformer((ohe,make_column_selector(dtype_include=object)),('passthrough',make_column_selector(dtype_exclude=object)),verbose_feature_names_out=False)
cs=np.linspace(.001,10,20)
scores=[]
for c in tqdm(cs):
    svm = SVC(kernel='poly',C=c)
    pipe=Pipeline([('ct',ct),('sc',sc),('svm',svm)])
    pipe.fit(X_train, y_train)
    pred = pipe.predict(X_test)
    scores.append([c,accuracy_score(y_test, pred)])

df_score=pd.DataFrame(scores,columns=['C','scores'])
df_score.sort_values('scores',ascending=False,ignore_index=True)[:20]

100%|██████████| 20/20 [00:17<00:00,  1.16it/s]

            C    scores
0    9.473737  0.947544
1   10.000000  0.947544
2    7.894947  0.947322
3    7.368684  0.947322
4    8.947474  0.947322
5    8.421211  0.947099
6    5.789895  0.946877
7    5.263632  0.946655
8    6.316158  0.946655
9    6.842421  0.946210
10   4.737368  0.945988
11   4.211105  0.945988
12   3.684842  0.944210
13   3.158579  0.943543
14   2.632316  0.942876
15   2.106053  0.940876
16   1.579789  0.939542
17   1.053526  0.933985
18   0.527263  0.916870
19   0.001000  0.763503

In [10]:
ohe=OneHotEncoder(sparse_output=False).set_output(transform='pandas')
sc=StandardScaler().set_output(transform='pandas')
ct=make_column_transformer((ohe,make_column_selector(dtype_include=object)),('passthrough',make_column_selector(dtype_exclude=object)),verbose_feature_names_out=False)
cs=np.linspace(.001,10,20)
scores=[]
for c in tqdm(cs):
    for d in [2,3,4]:
        svm = SVC(kernel='poly',C=c,degree=d)
        pipe=Pipeline([('ct',ct),('sc',sc),('svm',svm)])
        pipe.fit(X_train, y_train)
        pred = pipe.predict(X_test)
        scores.append([c,d,accuracy_score(y_test, pred)])
df_score=pd.DataFrame(scores,columns=['C','D','scores'])
df_score.sort_values('scores',ascending=False,ignore_index=True)[:20]

100%|██████████| 20/20 [00:43<00:00,  2.17s/it]

            C  D    scores
0    8.947474  4  0.953768
1   10.000000  4  0.953545
2    9.473737  4  0.953323
3    8.421211  4  0.952878
4    7.894947  4  0.952212
5    7.368684  4  0.950878
6    6.842421  4  0.950656
7    4.737368  4  0.950656
8    5.263632  4  0.950433
9    5.789895  4  0.950211
10   6.316158  4  0.950211
11   4.211105  4  0.949767
12   3.684842  4  0.949544
13   3.158579  4  0.947988
14   2.632316  4  0.947988
15   9.473737  3  0.947544
16  10.000000  3  0.947544
17   7.894947  3  0.947322
18   7.368684  3  0.947322
19   8.947474  3  0.947322

In [11]:
svm = SVC(kernel='rbf')
pipe=Pipeline([('ct',ct),('sc',sc),('svm',svm)])
pipe.fit(X_train, y_train)
pred = pipe.predict(X_test)
accuracy_score(y_test, pred)

0.9439875527895087

In [12]:
ohe=OneHotEncoder(sparse_output=False).set_output(transform='pandas')
sc=StandardScaler().set_output(transform='pandas')
ct=make_column_transformer((ohe,make_column_selector(dtype_include=object)),('passthrough',make_column_selector(dtype_exclude=object)),verbose_feature_names_out=False)
cs=np.linspace(.001,10,20)
gs = np.linspace(.01,10,20)
scores=[]
for c in tqdm(cs):
    for g in gs:
        svm = SVC(kernel='rbf',C=c,gamma=g)
        pipe=Pipeline([('ct',ct),('sc',sc),('svm',svm)])
        pipe.fit(X_train, y_train)
        pred = pipe.predict(X_test)
        scores.append([c,g,accuracy_score(y_test, pred)])
df_score=pd.DataFrame(scores,columns=['C','gamma','scores'])
df_score.sort_values('scores',ascending=False,ignore_index=True)[:20]

100%|██████████| 20/20 [09:08<00:00, 27.43s/it]

           C     gamma    scores
0   1.579789  1.061579  0.974883
1   2.106053  1.587368  0.974439
2   2.632316  2.113158  0.974439
3   4.737368  1.061579  0.974439
4   5.789895  1.061579  0.974439
5   5.263632  1.061579  0.974439
6   3.158579  2.113158  0.974439
7   1.579789  2.113158  0.974216
8   3.684842  1.061579  0.974216
9   4.211105  1.061579  0.974216
10  2.106053  2.113158  0.974216
11  6.316158  1.061579  0.974216
12  7.368684  1.061579  0.973994
13  7.894947  1.061579  0.973994
14  2.632316  1.587368  0.973994
15  3.684842  2.113158  0.973994
16  9.473737  1.061579  0.973772
17  8.947474  1.061579  0.973772
18  6.842421  1.061579  0.973772
19  2.632316  1.061579  0.973772

In [ ]:

scores = []
for c in tqdm(cs):
    for g in gs:
        # 2. This model will now train on the GPU automatically
        svm = SVC(kernel='rbf', C=c, gamma=g)
        pipe = Pipeline([('ct', ct), ('sc', sc), ('svm', svm)])
        
        pipe.fit(X_train, y_train)
        pred = pipe.predict(X_test)
        scores.append([c, g, accuracy_score(y_test, pred)])

 10%|█         | 2/20 [00:37<06:10, 20.59s/it]