In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error,r2_score
from sklearn.preprocessing import PolynomialFeatures, OneHotEncoder
from sklearn.linear_model import  ElasticNet, LinearRegression,Ridge,Lasso
from sklearn.compose import make_column_selector,make_column_transformer

In [2]:
df=pd.read_csv("F:\MACHINE LEARNING\SOMETHING\Datasets\Exp_Salaries.csv")
df.head(5)

,Salary,Years_Previous_Experience,Years Employed,Years_Education,Gender,Department,Number_Supervised
0,32782,1,0,7,Male,A,0
1,32920,3,15,9,Female,A,4
2,29548,6,5,1,Male,A,0
3,39828,6,18,5,Female,A,5
4,31528,11,3,3,Male,A,6

In [3]:
y = df['Salary']
X = df.drop('Salary', axis = 1)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Salary                     46 non-null     int64
 1   Years_Previous_Experience  46 non-null     int64
 2   Years Employed             46 non-null     int64
 3   Years_Education            46 non-null     int64
 4   Gender                     46 non-null     str
 5   Department                 46 non-null     str
 6   Number_Supervised          46 non-null     int64
dtypes: int64(5), str(2)
memory usage: 2.9 KB

In [6]:
df_num=X.select_dtypes(include='int')
df_obj=X.select_dtypes(exclude='int')

In [7]:
ohe=OneHotEncoder(sparse_output=False,drop='first').set_output(transform='pandas')

ct=make_column_transformer((ohe,make_column_selector(dtype_include=object)),
                           ("passthrough",make_column_selector(dtype_include=['int64','float64'])),verbose_feature_names_out=False)
ct=ct.set_output(transform='pandas')
x_ohe=ct.fit_transform(X)
x_ohe
# ohe_col=ohe.fit_transform(df_obj)

,Gender_Male,Department_B,Department_C,Department_D,Years_Previous_Experience,Years Employed,Years_Education,Number_Supervised
0,1.0,0.0,0.0,0.0,1,0,7,0
1,0.0,0.0,0.0,0.0,3,15,9,4
2,1.0,0.0,0.0,0.0,6,5,1,0
3,0.0,0.0,0.0,0.0,6,18,5,5
4,1.0,0.0,0.0,0.0,11,3,3,6
5,1.0,0.0,0.0,0.0,7,18,9,5
6,1.0,0.0,0.0,0.0,16,22,7,7
7,1.0,0.0,0.0,0.0,4,21,5,9
8,0.0,0.0,0.0,0.0,1,0,4,4
9,0.0,0.0,0.0,0.0,2,6,0,1
10,0.0,1.0,0.0,0.0,6,3,6,3
11,0.0,1.0,0.0,0.0,5,9,4,5
12,0.0,1.0,0.0,0.0,0,2,3,5
13,1.0,1.0,0.0,0.0,9,6,4,2
14,0.0,1.0,0.0,0.0,4,9,4,2
15,0.0,1.0,0.0,0.0,6,0,2,2
16,1.0,1.0,0.0,0.0,1,6,4,2
17,1.0,1.0,0.0,0.0,3,12,8,6
18,0.0,0.0,1.0,0.0,0,0,0,2
19,1.0,0.0,1.0,0.0,4,4,8,8
20,1.0,0.0,1.0,0.0,9,19,4,6
21,1.0,0.0,1.0,0.0,0,25,6,3
22,0.0,0.0,1.0,0.0,3,20,6,4
23,1.0,0.0,1.0,0.0,5,15,6,4
24,0.0,0.0,1.0,0.0,6,7,5,6
25,0.0,0.0,0.0,1.0,0,27,12,44
26,1.0,0.0,0.0,1.0,3,20,4,1
27,0.0,0.0,0.0,1.0,5,12,8,0
28,0.0,0.0,0.0,1.0,5,7,4,1
29,0.0,0.0,0.0,1.0,2,8,2,2
30,1.0,0.0,0.0,1.0,1,5,0,2
31,1.0,0.0,0.0,1.0,2,6,6,3
32,0.0,0.0,0.0,1.0,3,9,6,1
33,0.0,0.0,0.0,1.0,6,6,4,2
34,1.0,0.0,0.0,1.0,2,25,12,1
35,1.0,0.0,0.0,1.0,5,6,2,3
36,1.0,0.0,0.0,1.0,4,5,4,0
37,0.0,0.0,0.0,1.0,5,14,6,5
38,1.0,0.0,0.0,1.0,6,18,6,1
39,1.0,0.0,0.0,1.0,3,22,10,45
40,1.0,0.0,0.0,1.0,19,6,8,40
41,0.0,0.0,0.0,1.0,6,9,2,3
42,1.0,0.0,0.0,1.0,4,6,4,2
43,0.0,0.0,0.0,1.0,6,9,5,1
44,1.0,0.0,0.0,1.0,4,9,6,4
45,0.0,0.0,0.0,1.0,3,1,2,0

In [36]:
ohe

OneHotEncoder(drop='first', sparse_output=False)

In [7]:
# tr_data=pd.concat([df_num,ohe_col],axis=1)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(tr_data,y, test_size = 0.3, random_state = 26)

In [9]:
lr = LinearRegression()
lr.fit(X_train, y_train)
pred=lr.predict(X_test)

r2_score(y_test,pred)

0.5229253276468877

In [10]:
alpha = np.linspace(0.001,10,20)
ratio = np.linspace(0.001,1,20)

In [11]:
def ridge(a):
    ridge = Ridge(alpha=a)
    ridge.fit(X_train, y_train)
    pred=ridge.predict(X_test)
   
    print(f'at alpha :{a} r2 value: { r2_score(y_test,pred)}')
    return  r2_score(y_test,pred)
for a in alpha:
    ridge(a)

at alpha :0.001 r2 value: 0.5236383834172611
at alpha :0.5272631578947369 r2 value: 0.6794630257535978
at alpha :1.0535263157894736 r2 value: 0.7044025511876797
at alpha :1.5797894736842104 r2 value: 0.7079853550952572
at alpha :2.1060526315789474 r2 value: 0.7067726679279004
at alpha :2.6323157894736844 r2 value: 0.7045010180550864
at alpha :3.158578947368421 r2 value: 0.7021656406353278
at alpha :3.684842105263158 r2 value: 0.7000312451523112
at alpha :4.211105263157895 r2 value: 0.6981458044082289
at alpha :4.737368421052632 r2 value: 0.6964924960583102
at alpha :5.263631578947369 r2 value: 0.6950383091968906
at alpha :5.789894736842106 r2 value: 0.6937497989644756
at alpha :6.316157894736842 r2 value: 0.6925977269089929
at alpha :6.84242105263158 r2 value: 0.6915578792154843
at alpha :7.368684210526316 r2 value: 0.6906106390562496
at alpha :7.894947368421054 r2 value: 0.6897402399800747
at alpha :8.42121052631579 r2 value: 0.6889340240490531
at alpha :8.947473684210527 r2 value: 0.6881818035359051
at alpha :9.473736842105263 r2 value: 0.6874753424301122
at alpha :10.0 r2 value: 0.6868079460491391

In [12]:
def lasso(a):
    lasso = Lasso(alpha = a)
    lasso.fit(X_train, y_train)
    pred = lasso.predict(X_test)
    root_mean_squared_error(y_test, pred)
    print(f'at alpha :{a} r2 value: { r2_score(y_test,pred)}')
    return  r2_score(y_test,pred)
for a in alpha:
    lasso(a)

at alpha :0.001 r2 value: 0.5229272767055245
at alpha :0.5272631578947369 r2 value: 0.5239511324873213
at alpha :1.0535263157894736 r2 value: 0.524972870582483
at alpha :1.5797894736842104 r2 value: 0.525989634367735
at alpha :2.1060526315789474 r2 value: 0.5270043812927597
at alpha :2.6323157894736844 r2 value: 0.5280173222127496
at alpha :3.158578947368421 r2 value: 0.5290231726862626
at alpha :3.684842105263158 r2 value: 0.5300318004493842
at alpha :4.211105263157895 r2 value: 0.5310321201936897
at alpha :4.737368421052632 r2 value: 0.5320367688842043
at alpha :5.263631578947369 r2 value: 0.533031550571006
at alpha :5.789894736842106 r2 value: 0.5340235800246993
at alpha :6.316157894736842 r2 value: 0.5350128572452846
at alpha :6.84242105263158 r2 value: 0.5359993822327613
at alpha :7.368684210526316 r2 value: 0.5369920940090217
at alpha :7.894947368421054 r2 value: 0.5379730718158211
at alpha :8.42121052631579 r2 value: 0.5389512974909261
at alpha :8.947473684210527 r2 value: 0.539926771034337
at alpha :9.473736842105263 r2 value: 0.5408994924460542
at alpha :10.0 r2 value: 0.5418694617260783

In [25]:
elmodel={'alpha':[],
         'ratio':[],
         'r2':[]
}
def elastic_net(a, r):
    en = ElasticNet(alpha= a, l1_ratio= r)
    en.fit(X_train, y_train)
    pred = en.predict(X_test)
    root_mean_squared_error(y_test, pred)
    print(f'at alpha :{a} and ratio : {r} , r2_score:  {r2_score(y_test,pred)}')
    elmodel.append()
    return  r2_score(y_test,pred)
el_list=[]
for a in alpha:
    for r in ratio:
        el_list.append(elastic_net(a,r))

at alpha :0.001 and ratio : 0.001 , r2_score:  0.5442292523365577
at alpha :0.001 and ratio : 0.05357894736842105 , r2_score:  0.5431809494920106
at alpha :0.001 and ratio : 0.1061578947368421 , r2_score:  0.5421249550249748
at alpha :0.001 and ratio : 0.15873684210526315 , r2_score:  0.5410612004950666
at alpha :0.001 and ratio : 0.2113157894736842 , r2_score:  0.5399896173658607
at alpha :0.001 and ratio : 0.26389473684210524 , r2_score:  0.5389101360978155
at alpha :0.001 and ratio : 0.3164736842105263 , r2_score:  0.5378226857003472
at alpha :0.001 and ratio : 0.36905263157894735 , r2_score:  0.5367271963533811
at alpha :0.001 and ratio : 0.4216315789473684 , r2_score:  0.5356235947456932
at alpha :0.001 and ratio : 0.47421052631578947 , r2_score:  0.534511808979207
at alpha :0.001 and ratio : 0.5267894736842105 , r2_score:  0.5333917667440982
at alpha :0.001 and ratio : 0.5793684210526315 , r2_score:  0.5322633917040627
at alpha :0.001 and ratio : 0.6319473684210526 , r2_score:  0.5311266099107064
at alpha :0.001 and ratio : 0.6845263157894736 , r2_score:  0.5299813455507858
at alpha :0.001 and ratio : 0.7371052631578947 , r2_score:  0.5288275219865067
at alpha :0.001 and ratio : 0.7896842105263158 , r2_score:  0.5276650617449313
at alpha :0.001 and ratio : 0.8422631578947368 , r2_score:  0.526493888287303
at alpha :0.001 and ratio : 0.8948421052631579 , r2_score:  0.5253139189467698
at alpha :0.001 and ratio : 0.9474210526315789 , r2_score:  0.5241250753936797
at alpha :0.001 and ratio : 1.0 , r2_score:  0.5229272767055245
at alpha :0.5272631578947369 and ratio : 0.001 , r2_score:  0.6800851824953944
at alpha :0.5272631578947369 and ratio : 0.05357894736842105 , r2_score:  0.6808260665208354
at alpha :0.5272631578947369 and ratio : 0.1061578947368421 , r2_score:  0.6815933887600161
at alpha :0.5272631578947369 and ratio : 0.15873684210526315 , r2_score:  0.6823913203037604
at alpha :0.5272631578947369 and ratio : 0.2113157894736842 , r2_score:  0.6832253361222451
at alpha :0.5272631578947369 and ratio : 0.26389473684210524 , r2_score:  0.6841023249978981
at alpha :0.5272631578947369 and ratio : 0.3164736842105263 , r2_score:  0.685031342410852
at alpha :0.5272631578947369 and ratio : 0.36905263157894735 , r2_score:  0.6860244062708205
at alpha :0.5272631578947369 and ratio : 0.4216315789473684 , r2_score:  0.6870977328494579
at alpha :0.5272631578947369 and ratio : 0.47421052631578947 , r2_score:  0.6882735870548702
at alpha :0.5272631578947369 and ratio : 0.5267894736842105 , r2_score:  0.6895830845245275
at alpha :0.5272631578947369 and ratio : 0.5793684210526315 , r2_score:  0.6910704513187627
at alpha :0.5272631578947369 and ratio : 0.6319473684210526 , r2_score:  0.6927993966940312
at alpha :0.5272631578947369 and ratio : 0.6845263157894736 , r2_score:  0.6948619669742289
at alpha :0.5272631578947369 and ratio : 0.7371052631578947 , r2_score:  0.697387676656589
at alpha :0.5272631578947369 and ratio : 0.7896842105263158 , r2_score:  0.7005328007191443
at alpha :0.5272631578947369 and ratio : 0.8422631578947368 , r2_score:  0.7043442908348343
at alpha :0.5272631578947369 and ratio : 0.8948421052631579 , r2_score:  0.7077846193922823
at alpha :0.5272631578947369 and ratio : 0.9474210526315789 , r2_score:  0.7005861045760857
at alpha :0.5272631578947369 and ratio : 1.0 , r2_score:  0.5239511324873213
at alpha :1.0535263157894736 and ratio : 0.001 , r2_score:  0.6686747813864752
at alpha :1.0535263157894736 and ratio : 0.05357894736842105 , r2_score:  0.6697218031453436
at alpha :1.0535263157894736 and ratio : 0.1061578947368421 , r2_score:  0.6707962417941467
at alpha :1.0535263157894736 and ratio : 0.15873684210526315 , r2_score:  0.671899571439334
at alpha :1.0535263157894736 and ratio : 0.2113157894736842 , r2_score:  0.6730348239011221
at alpha :1.0535263157894736 and ratio : 0.26389473684210524 , r2_score:  0.6742055072780035
at alpha :1.0535263157894736 and ratio : 0.3164736842105263 , r2_score:  0.6754159232209613
at alpha :1.0535263157894736 and ratio : 0.36905263157894735 , r2_score:  0.6766721801182631
at alpha :1.0535263157894736 and ratio : 0.4216315789473684 , r2_score:  0.6779826219970501
at alpha :1.0535263157894736 and ratio : 0.47421052631578947 , r2_score:  0.6793581710319083
at alpha :1.0535263157894736 and ratio : 0.5267894736842105 , r2_score:  0.6808153759197377
at alpha :1.0535263157894736 and ratio : 0.5793684210526315 , r2_score:  0.6823789940324007
at alpha :1.0535263157894736 and ratio : 0.6319473684210526 , r2_score:  0.6840881767967406
at alpha :1.0535263157894736 and ratio : 0.6845263157894736 , r2_score:  0.6860088081703974
at alpha :1.0535263157894736 and ratio : 0.7371052631578947 , r2_score:  0.6882559709608376
at alpha :1.0535263157894736 and ratio : 0.7896842105263158 , r2_score:  0.6910507161149414
at alpha :1.0535263157894736 and ratio : 0.8422631578947368 , r2_score:  0.6948402815200224
at alpha :1.0535263157894736 and ratio : 0.8948421052631579 , r2_score:  0.7005112214240741
at alpha :1.0535263157894736 and ratio : 0.9474210526315789 , r2_score:  0.7077800351602315
at alpha :1.0535263157894736 and ratio : 1.0 , r2_score:  0.524972870582483
at alpha :1.5797894736842104 and ratio : 0.001 , r2_score:  0.6597971858215114
at alpha :1.5797894736842104 and ratio : 0.05357894736842105 , r2_score:  0.6610841297577638
at alpha :1.5797894736842104 and ratio : 0.1061578947368421 , r2_score:  0.6624096125265644
at alpha :1.5797894736842104 and ratio : 0.15873684210526315 , r2_score:  0.6637758223094881
at alpha :1.5797894736842104 and ratio : 0.2113157894736842 , r2_score:  0.665185336902157
at alpha :1.5797894736842104 and ratio : 0.26389473684210524 , r2_score:  0.6666410819265557
at alpha :1.5797894736842104 and ratio : 0.3164736842105263 , r2_score:  0.6681467769660258
at alpha :1.5797894736842104 and ratio : 0.36905263157894735 , r2_score:  0.6697070364245468
at alpha :1.5797894736842104 and ratio : 0.4216315789473684 , r2_score:  0.6713311192559637
at alpha :1.5797894736842104 and ratio : 0.47421052631578947 , r2_score:  0.6730210683843709
at alpha :1.5797894736842104 and ratio : 0.5267894736842105 , r2_score:  0.6747902460754088
at alpha :1.5797894736842104 and ratio : 0.5793684210526315 , r2_score:  0.676656085114149
at alpha :1.5797894736842104 and ratio : 0.6319473684210526 , r2_score:  0.6786436368910991
at alpha :1.5797894736842104 and ratio : 0.6845263157894736 , r2_score:  0.6807958664228373
at alpha :1.5797894736842104 and ratio : 0.7371052631578947 , r2_score:  0.6831912951174033
at alpha :1.5797894736842104 and ratio : 0.7896842105263158 , r2_score:  0.6859850652730553
at alpha :1.5797894736842104 and ratio : 0.8422631578947368 , r2_score:  0.689537375766636
at alpha :1.5797894736842104 and ratio : 0.8948421052631579 , r2_score:  0.6948104375263968
at alpha :1.5797894736842104 and ratio : 0.9474210526315789 , r2_score:  0.7043001333764696
at alpha :1.5797894736842104 and ratio : 1.0 , r2_score:  0.525989634367735
at alpha :2.1060526315789474 and ratio : 0.001 , r2_score:  0.6524224305007713
at alpha :2.1060526315789474 and ratio : 0.05357894736842105 , r2_score:  0.6538682587738162
at alpha :2.1060526315789474 and ratio : 0.1061578947368421 , r2_score:  0.6553666789643122
at alpha :2.1060526315789474 and ratio : 0.15873684210526315 , r2_score:  0.65692053921568
at alpha :2.1060526315789474 and ratio : 0.2113157894736842 , r2_score:  0.6585329873197538
at alpha :2.1060526315789474 and ratio : 0.26389473684210524 , r2_score:  0.6602076641664234
at alpha :2.1060526315789474 and ratio : 0.3164736842105263 , r2_score:  0.6619484821273904
at alpha :2.1060526315789474 and ratio : 0.36905263157894735 , r2_score:  0.6637603372996032
at alpha :2.1060526315789474 and ratio : 0.4216315789473684 , r2_score:  0.6656490893054613
at alpha :2.1060526315789474 and ratio : 0.47421052631578947 , r2_score:  0.667622141674697
at alpha :2.1060526315789474 and ratio : 0.5267894736842105 , r2_score:  0.6696892835228108
at alpha :2.1060526315789474 and ratio : 0.5793684210526315 , r2_score:  0.6718701914326299
at alpha :2.1060526315789474 and ratio : 0.6319473684210526 , r2_score:  0.674173512365336
at alpha :2.1060526315789474 and ratio : 0.6845263157894736 , r2_score:  0.676637037991092
at alpha :2.1060526315789474 and ratio : 0.7371052631578947 , r2_score:  0.6793197653925651
at alpha :2.1060526315789474 and ratio : 0.7896842105263158 , r2_score:  0.6823358551448109
at alpha :2.1060526315789474 and ratio : 0.8422631578947368 , r2_score:  0.6859586328298777
at alpha :2.1060526315789474 and ratio : 0.8948421052631579 , r2_score:  0.6909928983389106
at alpha :2.1060526315789474 and ratio : 0.9474210526315789 , r2_score:  0.7004478585164071
at alpha :2.1060526315789474 and ratio : 1.0 , r2_score:  0.5270043812927597
at alpha :2.6323157894736844 and ratio : 0.001 , r2_score:  0.6461865785339568
at alpha :2.6323157894736844 and ratio : 0.05357894736842105 , r2_score:  0.647727873846255
at alpha :2.6323157894736844 and ratio : 0.1061578947368421 , r2_score:  0.6493353763798604
at alpha :2.6323157894736844 and ratio : 0.15873684210526315 , r2_score:  0.6510130227032309
at alpha :2.6323157894736844 and ratio : 0.2113157894736842 , r2_score:  0.652765087131932
at alpha :2.6323157894736844 and ratio : 0.26389473684210524 , r2_score:  0.6545962659437932
at alpha :2.6323157894736844 and ratio : 0.3164736842105263 , r2_score:  0.6565117819814591
at alpha :2.6323157894736844 and ratio : 0.36905263157894735 , r2_score:  0.6585175410260558
at alpha :2.6323157894736844 and ratio : 0.4216315789473684 , r2_score:  0.6606203742527217
at alpha :2.6323157894736844 and ratio : 0.47421052631578947 , r2_score:  0.6628284289728719
at alpha :2.6323157894736844 and ratio : 0.5267894736842105 , r2_score:  0.6651518258695703
at alpha :2.6323157894736844 and ratio : 0.5793684210526315 , r2_score:  0.6676038207643242
at alpha :2.6323157894736844 and ratio : 0.6319473684210526 , r2_score:  0.6702036503235016
at alpha :2.6323157894736844 and ratio : 0.6845263157894736 , r2_score:  0.6729862813488918
at alpha :2.6323157894736844 and ratio : 0.7371052631578947 , r2_score:  0.6759843911502366
at alpha :2.6323157894736844 and ratio : 0.7896842105263158 , r2_score:  0.6792976364854508
at alpha :2.6323157894736844 and ratio : 0.8422631578947368 , r2_score:  0.6831438721760964
at alpha :2.6323157894736844 and ratio : 0.8948421052631579 , r2_score:  0.6881734842673035
at alpha :2.6323157894736844 and ratio : 0.9474210526315789 , r2_score:  0.6972664680643494
at alpha :2.6323157894736844 and ratio : 1.0 , r2_score:  0.5280173222127496
at alpha :3.158578947368421 and ratio : 0.001 , r2_score:  0.6408602699649321
at alpha :3.158578947368421 and ratio : 0.05357894736842105 , r2_score:  0.6424511117538241
at alpha :3.158578947368421 and ratio : 0.1061578947368421 , r2_score:  0.6441201245898296
at alpha :3.158578947368421 and ratio : 0.15873684210526315 , r2_score:  0.6458725624868533
at alpha :3.158578947368421 and ratio : 0.2113157894736842 , r2_score:  0.6477141227655898
at alpha :3.158578947368421 and ratio : 0.26389473684210524 , r2_score:  0.6496510261234865
at alpha :3.158578947368421 and ratio : 0.3164736842105263 , r2_score:  0.6516901108294342
at alpha :3.158578947368421 and ratio : 0.36905263157894735 , r2_score:  0.6538389675383786
at alpha :3.158578947368421 and ratio : 0.4216315789473684 , r2_score:  0.6561061421986392
at alpha :3.158578947368421 and ratio : 0.47421052631578947 , r2_score:  0.658501457498037
at alpha :3.158578947368421 and ratio : 0.5267894736842105 , r2_score:  0.6610365495182434
at alpha :3.158578947368421 and ratio : 0.5793684210526315 , r2_score:  0.6637258148967975
at alpha :3.158578947368421 and ratio : 0.6319473684210526 , r2_score:  0.666588190400669
at alpha :3.158578947368421 and ratio : 0.6845263157894736 , r2_score:  0.6696507589196528
at alpha :3.158578947368421 and ratio : 0.7371052631578947 , r2_score:  0.6729678925262174
at alpha :3.158578947368421 and ratio : 0.7896842105263158 , r2_score:  0.6765975136933026
at alpha :3.158578947368421 and ratio : 0.8422631578947368 , r2_score:  0.6807289456691066
at alpha :3.158578947368421 and ratio : 0.8948421052631579 , r2_score:  0.685906286316224
at alpha :3.158578947368421 and ratio : 0.9474210526315789 , r2_score:  0.6947109260868898
at alpha :3.158578947368421 and ratio : 1.0 , r2_score:  0.5290231726862626
at alpha :3.684842105263158 and ratio : 0.001 , r2_score:  0.636273423208748
at alpha :3.684842105263158 and ratio : 0.05357894736842105 , r2_score:  0.6378816993313421
at alpha :3.684842105263158 and ratio : 0.1061578947368421 , r2_score:  0.6395780382709395
at alpha :3.684842105263158 and ratio : 0.15873684210526315 , r2_score:  0.6413690757381267
at alpha :3.684842105263158 and ratio : 0.2113157894736842 , r2_score:  0.6432620664768096
at alpha :3.684842105263158 and ratio : 0.26389473684210524 , r2_score:  0.6452649550189966
at alpha :3.684842105263158 and ratio : 0.3164736842105263 , r2_score:  0.647386476047036
at alpha :3.684842105263158 and ratio : 0.36905263157894735 , r2_score:  0.6496362882353586
at alpha :3.684842105263158 and ratio : 0.4216315789473684 , r2_score:  0.6520251635345786
at alpha :3.684842105263158 and ratio : 0.47421052631578947 , r2_score:  0.6545652729447933
at alpha :3.684842105263158 and ratio : 0.5267894736842105 , r2_score:  0.6572706487284374
at alpha :3.684842105263158 and ratio : 0.5793684210526315 , r2_score:  0.6601579866648604
at alpha :3.684842105263158 and ratio : 0.6319473684210526 , r2_score:  0.6632481444644923
at alpha :3.684842105263158 and ratio : 0.6845263157894736 , r2_score:  0.666569176478486
at alpha :3.684842105263158 and ratio : 0.7371052631578947 , r2_score:  0.6701670498521126
at alpha :3.684842105263158 and ratio : 0.7896842105263158 , r2_score:  0.6741165056063728
at alpha :3.684842105263158 and ratio : 0.8422631578947368 , r2_score:  0.6785599909540265
at alpha :3.684842105263158 and ratio : 0.8948421052631579 , r2_score:  0.6839678903553863
at alpha :3.684842105263158 and ratio : 0.9474210526315789 , r2_score:  0.6926198653885585
at alpha :3.684842105263158 and ratio : 1.0 , r2_score:  0.5300318004493842
at alpha :4.211105263157895 and ratio : 0.001 , r2_score:  0.6322934820362911
at alpha :4.211105263157895 and ratio : 0.05357894736842105 , r2_score:  0.6338974404365796
at alpha :4.211105263157895 and ratio : 0.1061578947368421 , r2_score:  0.6355972109659673
at alpha :4.211105263157895 and ratio : 0.15873684210526315 , r2_score:  0.6374008125670076
at alpha :4.211105263157895 and ratio : 0.2113157894736842 , r2_score:  0.6393170788967604
at alpha :4.211105263157895 and ratio : 0.26389473684210524 , r2_score:  0.6413557471159341
at alpha :4.211105263157895 and ratio : 0.3164736842105263 , r2_score:  0.6435275795768683
at alpha :4.211105263157895 and ratio : 0.36905263157894735 , r2_score:  0.6458445159111823
at alpha :4.211105263157895 and ratio : 0.4216315789473684 , r2_score:  0.6483195845995429
at alpha :4.211105263157895 and ratio : 0.47421052631578947 , r2_score:  0.6509682518951465
at alpha :4.211105263157895 and ratio : 0.5267894736842105 , r2_score:  0.6538073679750457
at alpha :4.211105263157895 and ratio : 0.5793684210526315 , r2_score:  0.6568568020444665
at alpha :4.211105263157895 and ratio : 0.6319473684210526 , r2_score:  0.6601405302408381
at alpha :4.211105263157895 and ratio : 0.6845263157894736 , r2_score:  0.6636892511049564
at alpha :4.211105263157895 and ratio : 0.7371052631578947 , r2_score:  0.6675462216480859
at alpha :4.211105263157895 and ratio : 0.7896842105263158 , r2_score:  0.6717984511743046
at alpha :4.211105263157895 and ratio : 0.8422631578947368 , r2_score:  0.6765551025957142
at alpha :4.211105263157895 and ratio : 0.8948421052631579 , r2_score:  0.682239810696218
at alpha :4.211105263157895 and ratio : 0.9474210526315789 , r2_score:  0.6908676326977758
at alpha :4.211105263157895 and ratio : 1.0 , r2_score:  0.5310321201936897
at alpha :4.737368421052632 and ratio : 0.001 , r2_score:  0.6288151168828016
at alpha :4.737368421052632 and ratio : 0.05357894736842105 , r2_score:  0.6304004435614745
at alpha :4.737368421052632 and ratio : 0.1061578947368421 , r2_score:  0.6320873425398239
at alpha :4.737368421052632 and ratio : 0.15873684210526315 , r2_score:  0.6338851287072116
at alpha :4.737368421052632 and ratio : 0.2113157894736842 , r2_score:  0.6358041573402966
at alpha :4.737368421052632 and ratio : 0.26389473684210524 , r2_score:  0.637855931740825
at alpha :4.737368421052632 and ratio : 0.3164736842105263 , r2_score:  0.640053259754235
at alpha :4.737368421052632 and ratio : 0.36905263157894735 , r2_score:  0.6424104421500434
at alpha :4.737368421052632 and ratio : 0.4216315789473684 , r2_score:  0.6449435073887599
at alpha :4.737368421052632 and ratio : 0.47421052631578947 , r2_score:  0.6476705199785285
at alpha :4.737368421052632 and ratio : 0.5267894736842105 , r2_score:  0.6506120166583389
at alpha :4.737368421052632 and ratio : 0.5793684210526315 , r2_score:  0.6537912162536264
at alpha :4.737368421052632 and ratio : 0.6319473684210526 , r2_score:  0.6572369701101
at alpha :4.737368421052632 and ratio : 0.6845263157894736 , r2_score:  0.6609836009037033
at alpha :4.737368421052632 and ratio : 0.7371052631578947 , r2_score:  0.6650775645849087
at alpha :4.737368421052632 and ratio : 0.7896842105263158 , r2_score:  0.6695915449511564
at alpha :4.737368421052632 and ratio : 0.8422631578947368 , r2_score:  0.674675286718484
at alpha :4.737368421052632 and ratio : 0.8948421052631579 , r2_score:  0.6806605639133383
at alpha :4.737368421052632 and ratio : 0.9474210526315789 , r2_score:  0.6893590785562422
at alpha :4.737368421052632 and ratio : 1.0 , r2_score:  0.5320367688842043
at alpha :5.263631578947369 and ratio : 0.001 , r2_score:  0.6257536995642994
at alpha :5.263631578947369 and ratio : 0.05357894736842105 , r2_score:  0.6273115262627529
at alpha :5.263631578947369 and ratio : 0.1061578947368421 , r2_score:  0.628974908592547
at alpha :5.263631578947369 and ratio : 0.15873684210526315 , r2_score:  0.6307543531558978
at alpha :5.263631578947369 and ratio : 0.2113157894736842 , r2_score:  0.6326616375780174
at alpha :5.263631578947369 and ratio : 0.26389473684210524 , r2_score:  0.6347099497671684
at alpha :5.263631578947369 and ratio : 0.3164736842105263 , r2_score:  0.6369140900059256
at alpha :5.263631578947369 and ratio : 0.36905263157894735 , r2_score:  0.6392903530629573
at alpha :5.263631578947369 and ratio : 0.4216315789473684 , r2_score:  0.6418581032362343
at alpha :5.263631578947369 and ratio : 0.47421052631578947 , r2_score:  0.6446383891796879
at alpha :5.263631578947369 and ratio : 0.5267894736842105 , r2_score:  0.6476554946124274
at alpha :5.263631578947369 and ratio : 0.5793684210526315 , r2_score:  0.6509373920291479
at alpha :5.263631578947369 and ratio : 0.6319473684210526 , r2_score:  0.6545168777604622
at alpha :5.263631578947369 and ratio : 0.6845263157894736 , r2_score:  0.6584330815223265
at alpha :5.263631578947369 and ratio : 0.7371052631578947 , r2_score:  0.6627383891736336
at alpha :5.263631578947369 and ratio : 0.7896842105263158 , r2_score:  0.6675072247581191
at alpha :5.263631578947369 and ratio : 0.8422631578947368 , r2_score:  0.6728921106556714
at alpha :5.263631578947369 and ratio : 0.8948421052631579 , r2_score:  0.6791883785014032
at alpha :5.263631578947369 and ratio : 0.9474210526315789 , r2_score:  0.6880299822475656
at alpha :5.263631578947369 and ratio : 1.0 , r2_score:  0.533031550571006
at alpha :5.789894736842106 and ratio : 0.001 , r2_score:  0.6230407352832628
at alpha :5.789894736842106 and ratio : 0.05357894736842105 , r2_score:  0.6245660144210612
at alpha :5.789894736842106 and ratio : 0.1061578947368421 , r2_score:  0.6261992862614578
at alpha :5.789894736842106 and ratio : 0.15873684210526315 , r2_score:  0.6279521061054686

In [26]:
elmodel

{'alpha': np.float64(10.0), 'ratio': np.float64(1.0), 'r2': 0.5418694617260783}