In [8]:
from sklearnex import patch_sklearn
patch_sklearn()
import pandas as pd

from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import accuracy_score, r2_score

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.compose import make_column_selector,make_column_transformer
from sklearn.pipeline import Pipeline
from tqdm import tqdm

Extension for Scikit-learn* enabled (https://github.com/uxlfoundation/scikit-learn-intelex)

In [5]:
df=pd.read_csv("F:\MACHINE LEARNING\SessionsMaterial\Cases\Vehicle Silhouettes\Vehicle.csv")
df.head()

,Comp,Circ,D.Circ,Rad.Ra,Pr.Axis.Ra,Max.L.Ra,Scat.Ra,Elong,Pr.Axis.Rect,Max.L.Rect,Sc.Var.Maxis,Sc.Var.maxis,Ra.Gyr,Skew.Maxis,Skew.maxis,Kurt.maxis,Kurt.Maxis,Holl.Ra,Class
0,95,48,83,178,72,10,162,42,20,159,176,379,184,70,6,16,187,197,van
1,91,41,84,141,57,9,149,45,19,143,170,330,158,72,9,14,189,199,van
2,104,50,106,209,66,10,207,32,23,158,223,635,220,73,14,9,188,196,saab
3,93,41,82,159,63,9,144,46,19,143,160,309,127,63,6,10,199,207,van
4,85,44,70,205,103,52,149,45,19,144,241,325,188,127,9,11,180,183,bus

In [10]:
X,y=df.drop("Class",axis=1),df.Class
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.3,random_state=26,stratify=y)

In [11]:
sc=StandardScaler().set_output(transform='pandas')
learn_r = np.linspace(0.01, 0.9, 10)
max_depth = [None, 2,3,4]
n_est = [25,50,100]
scores = []
for r in tqdm(learn_r):
    for m in max_depth:
        for n in n_est:
            gbm = GradientBoostingClassifier(random_state=26, learning_rate=r, max_depth= m, n_estimators=n)
            pipe=Pipeline([('sc',sc),('gbm',gbm)])
            pipe.fit(X_train, y_train)
            pred = pipe.predict(X_test)
            scores.append([r,m,n, accuracy_score(y_test, pred)])
score_df=pd.DataFrame(scores,columns=["learning_rate",'max_depth','n_estimators','accuracy_score(' ])
score_df.sort_values(by="accuracy_score(",ascending=False,ignore_index=True)[:20]

100%|██████████| 10/10 [01:38<00:00,  9.87s/it]

In [14]:
score_df

     learning_rate  max_depth  n_estimators  accuracy_score(
0             0.01        NaN            25         0.696850
1             0.01        NaN            50         0.696850
2             0.01        NaN           100         0.700787
3             0.01        2.0            25         0.653543
4             0.01        2.0            50         0.645669
..             ...        ...           ...              ...
115           0.90        3.0            50         0.755906
116           0.90        3.0           100         0.763780
117           0.90        4.0            25         0.728346
118           0.90        4.0            50         0.716535
119           0.90        4.0           100         0.736220

[120 rows x 4 columns]

In [13]:
from catboost  import CatBoostClassifier
learn_r = np.linspace(0.01, 0.9, 10)
max_depth = [None, 2,3,4]
n_est = [25,50,100]
scores = []
for r in tqdm(learn_r):
    for m in max_depth:
        for n in n_est:
            gbm = CatBoostClassifier(random_state=26, learning_rate=r, max_depth= m, n_estimators=n, verbose = False)
            gbm.fit(X_train, y_train)
            pred = gbm.predict(X_test)
            scores.append([r,m,n, accuracy_score(y_test, pred)])
score_df=pd.DataFrame(scores,columns=["learning_rate",'max_depth','n_estimators','accuracy_score(' ])
score_df.sort_values(by="accuracy_score(",ascending=False,ignore_index=True)[:20]

100%|██████████| 10/10 [00:18<00:00,  1.81s/it]

    learning_rate  max_depth  n_estimators  accuracy_score(
0        0.702222        4.0            50         0.783465
1        0.702222        4.0           100         0.779528
2        0.801111        2.0           100         0.779528
3        0.504444        4.0           100         0.775591
4        0.504444        2.0           100         0.775591
5        0.702222        2.0           100         0.775591
6        0.306667        3.0           100         0.771654
7        0.207778        NaN           100         0.771654
8        0.603333        4.0           100         0.771654
9        0.603333        2.0           100         0.767717
10       0.108889        4.0           100         0.767717
11       0.306667        4.0           100         0.767717
12       0.207778        4.0           100         0.767717
13       0.702222        4.0            25         0.767717
14       0.603333        3.0           100         0.767717
15       0.702222        NaN           100         0.767717
16       0.900000        3.0            25         0.763780
17       0.405556        3.0           100         0.763780
18       0.801111        3.0            25         0.763780
19       0.801111        4.0           100         0.763780

In [15]:
from lightgbm import LGBMClassifier
learn_r = np.linspace(0.01, 0.9, 10)
max_depth = [None, 2,3,4]
n_est = [25,50,100]
scores = []
for r in tqdm(learn_r):
    for m in max_depth:
        for n in n_est:
            gbm = LGBMClassifier(random_state=26, learning_rate=r, max_depth= m, n_estimators=n, verbose = -1)
            gbm.fit(X_train, y_train)
            pred = gbm.predict(X_test)
            scores.append([r,m,n, accuracy_score(y_test, pred)])
score_df=pd.DataFrame(scores,columns=["learning_rate",'max_depth','n_estimators','accuracy_score(' ])
score_df.sort_values(by="accuracy_score(",ascending=False,ignore_index=True)[:20]

100%|██████████| 10/10 [00:11<00:00,  1.12s/it]

    learning_rate  max_depth  n_estimators  accuracy_score(
0        0.702222        NaN            25         0.803150
1        0.405556        2.0            50         0.799213
2        0.504444        2.0           100         0.799213
3        0.603333        2.0            50         0.799213
4        0.702222        3.0            50         0.795276
5        0.801111        2.0           100         0.795276
6        0.900000        2.0            50         0.795276
7        0.504444        2.0            50         0.791339
8        0.504444        2.0            25         0.791339
9        0.900000        2.0           100         0.791339
10       0.603333        2.0            25         0.791339
11       0.702222        3.0           100         0.791339
12       0.900000        2.0            25         0.791339
13       0.603333        3.0            25         0.787402
14       0.801111        2.0            25         0.787402
15       0.702222        3.0            25         0.787402
16       0.306667        NaN            50         0.787402
17       0.306667        NaN           100         0.787402
18       0.306667        2.0            50         0.787402
19       0.405556        3.0           100         0.783465