In [1]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np
from tqdm import tqdm
from sklearn.metrics import accuracy_score
from sklearn.ensemble import VotingClassifier

In [2]:
heart = pd.read_csv("F:\MACHINE LEARNING\SOMETHING\Datasets\heart.csv")
X,y=heart.drop('target',axis=1),heart.target
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.3,random_state=26,stratify=y)

In [3]:
dtc=DecisionTreeClassifier(random_state=26)
lr=LogisticRegression()
knn=KNeighborsClassifier()
voting=VotingClassifier([('TREE',dtc),('LR',lr),('KNN',knn)])
voting.fit(X_train,y_train)
y_pred=voting.predict(X_test)
accuracy_score(y_test,y_pred)

C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.8131868131868132

In [4]:
df=pd.read_csv("F:\MACHINE LEARNING\SessionsMaterial\Cases\Wisconsin\BreastCancer.csv",index_col=0)
X,y=df.drop('Class',axis=1),df['Class']
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=26,test_size=.3,stratify=y)
df.head()

,Clump,UniCell_Size,Uni_CellShape,MargAdh,SEpith,BareN,BChromatin,NoemN,Mitoses,Class
Code,,,,,,,,,,
61634,5,4,3,1,2,2,2,3,1,Benign
63375,9,1,2,6,4,10,7,7,2,Malignant
76389,10,4,7,2,2,8,6,1,1,Malignant
95719,6,10,10,10,8,10,7,10,7,Malignant
128059,1,1,1,1,2,5,5,1,1,Benign

In [5]:
dtc=DecisionTreeClassifier(random_state=26)
lr=LogisticRegression()
knn=KNeighborsClassifier()
voting=VotingClassifier([('TREE',dtc),('LR',lr),('KNN',knn)])
voting.fit(X_train,y_train)
y_pred=voting.predict(X_test)
accuracy_score(y_test,y_pred)

0.9571428571428572

In [6]:
depths=[None,2,3,4,5]
solvers=['lbfgs','saga','sag','liblinear']
Ks=[2,5,10]
scores=[]
for d in tqdm(depths):
    for s in solvers:
        for k in Ks:
            dtc=DecisionTreeClassifier(random_state=26,max_depth=d)
            lr=LogisticRegression(solver=s)
            knn=KNeighborsClassifier(n_neighbors=k)
            voting=VotingClassifier([('TREE',dtc),('LR',lr),('KNN',knn)],voting='hard')
            voting.fit(X_train,y_train)
            y_pred=voting.predict(X_test)
            scores.append([d,s,k,accuracy_score(y_test,y_pred)])
pd.DataFrame(scores,columns=['DEPTH','SOLVER','N_NEIGHBORS','ACCURACY']).sort_values(by='ACCURACY',ascending=False)

  0%|          | 0/5 [00:00<?, ?it/s]C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
 20%|██        | 1/5 [00:00<00:01,  2.82it/s]C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
 40%|████      | 2/5 [00:00<00:01,  2.77it/s]C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
 60%|██████    | 3/5 [00:01<00:00,  2.81it/s]C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
 80%|████████  | 4/5 [00:01<00:00,  2.89it/s]C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
100%|██████████| 5/5 [00:01<00:00,  2.88it/s]

    DEPTH     SOLVER  N_NEIGHBORS  ACCURACY
2     NaN      lbfgs           10  0.966667
14    2.0      lbfgs           10  0.966667
26    3.0      lbfgs           10  0.966667
38    4.0      lbfgs           10  0.966667
50    5.0      lbfgs           10  0.966667
8     NaN        sag           10  0.961905
9     NaN  liblinear            2  0.961905
21    2.0  liblinear            2  0.961905
15    2.0       saga            2  0.961905
17    2.0       saga           10  0.961905
23    2.0  liblinear           10  0.961905
3     NaN       saga            2  0.961905
20    2.0        sag           10  0.961905
27    3.0       saga            2  0.961905
47    4.0  liblinear           10  0.961905
45    4.0  liblinear            2  0.961905
51    5.0       saga            2  0.961905
57    5.0  liblinear            2  0.961905
59    5.0  liblinear           10  0.961905
53    5.0       saga           10  0.961905
35    3.0  liblinear           10  0.961905
32    3.0        sag           10  0.961905
41    4.0       saga           10  0.961905
39    4.0       saga            2  0.961905
29    3.0       saga           10  0.961905
33    3.0  liblinear            2  0.961905
11    NaN  liblinear           10  0.961905
5     NaN       saga           10  0.961905
44    4.0        sag           10  0.961905
56    5.0        sag           10  0.961905
28    3.0       saga            5  0.957143
48    5.0      lbfgs            2  0.957143
12    2.0      lbfgs            2  0.957143
16    2.0       saga            5  0.957143
22    2.0  liblinear            5  0.957143
24    3.0      lbfgs            2  0.957143
4     NaN       saga            5  0.957143
6     NaN        sag            2  0.957143
0     NaN      lbfgs            2  0.957143
1     NaN      lbfgs            5  0.957143
10    NaN  liblinear            5  0.957143
13    2.0      lbfgs            5  0.957143
18    2.0        sag            2  0.957143
25    3.0      lbfgs            5  0.957143
52    5.0       saga            5  0.957143
54    5.0        sag            2  0.957143
40    4.0       saga            5  0.957143
42    4.0        sag            2  0.957143
37    4.0      lbfgs            5  0.957143
30    3.0        sag            2  0.957143
34    3.0  liblinear            5  0.957143
36    4.0      lbfgs            2  0.957143
58    5.0  liblinear            5  0.957143
49    5.0      lbfgs            5  0.957143
46    4.0  liblinear            5  0.957143
7     NaN        sag            5  0.952381
19    2.0        sag            5  0.952381
31    3.0        sag            5  0.952381
43    4.0        sag            5  0.952381
55    5.0        sag            5  0.952381

In [7]:
depths=[None,2,3,4,5]
solvers=['lbfgs','saga','sag','liblinear']
Ks=[2,5,10]
scores=[]
for d in tqdm(depths):
    for s in solvers:
        for k in Ks:
            dtc=DecisionTreeClassifier(random_state=26,max_depth=d)
            lr=LogisticRegression(solver=s)
            knn=KNeighborsClassifier(n_neighbors=k)
            voting=VotingClassifier([('TREE',dtc),('LR',lr),('KNN',knn)],voting='soft')
            voting.fit(X_train,y_train)
            y_pred=voting.predict(X_test)
            scores.append([d,s,k,accuracy_score(y_test,y_pred)])
pd.DataFrame(scores,columns=['DEPTH','SOLVER','N_NEIGHBORS','ACCURACY']).sort_values(by='ACCURACY',ascending=False)

  0%|          | 0/5 [00:00<?, ?it/s]C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
 20%|██        | 1/5 [00:00<00:01,  2.75it/s]C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
 40%|████      | 2/5 [00:00<00:00,  3.02it/s]C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
 60%|██████    | 3/5 [00:00<00:00,  3.15it/s]C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
 80%|████████  | 4/5 [00:01<00:00,  3.20it/s]C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
100%|██████████| 5/5 [00:01<00:00,  3.05it/s]

    DEPTH     SOLVER  N_NEIGHBORS  ACCURACY
27    3.0       saga            2  0.971429
24    3.0      lbfgs            2  0.971429
33    3.0  liblinear            2  0.971429
30    3.0        sag            2  0.971429
36    4.0      lbfgs            2  0.971429
39    4.0       saga            2  0.971429
45    4.0  liblinear            2  0.971429
42    4.0        sag            2  0.971429
21    2.0  liblinear            2  0.966667
18    2.0        sag            2  0.966667
15    2.0       saga            2  0.966667
12    2.0      lbfgs            2  0.966667
19    2.0        sag            5  0.961905
17    2.0       saga           10  0.961905
16    2.0       saga            5  0.961905
20    2.0        sag           10  0.961905
8     NaN        sag           10  0.961905
9     NaN  liblinear            2  0.961905
14    2.0      lbfgs           10  0.961905
13    2.0      lbfgs            5  0.961905
23    2.0  liblinear           10  0.961905
22    2.0  liblinear            5  0.961905
11    NaN  liblinear           10  0.961905
6     NaN        sag            2  0.961905
0     NaN      lbfgs            2  0.961905
2     NaN      lbfgs           10  0.961905
3     NaN       saga            2  0.961905
5     NaN       saga           10  0.961905
59    5.0  liblinear           10  0.961905
44    4.0        sag           10  0.961905
46    4.0  liblinear            5  0.961905
47    4.0  liblinear           10  0.961905
26    3.0      lbfgs           10  0.961905
25    3.0      lbfgs            5  0.961905
29    3.0       saga           10  0.961905
31    3.0        sag            5  0.961905
35    3.0  liblinear           10  0.961905
34    3.0  liblinear            5  0.961905
32    3.0        sag           10  0.961905
38    4.0      lbfgs           10  0.961905
41    4.0       saga           10  0.961905
40    4.0       saga            5  0.961905
43    4.0        sag            5  0.961905
28    3.0       saga            5  0.961905
57    5.0  liblinear            2  0.961905
54    5.0        sag            2  0.961905
56    5.0        sag           10  0.961905
53    5.0       saga           10  0.961905
48    5.0      lbfgs            2  0.961905
50    5.0      lbfgs           10  0.961905
51    5.0       saga            2  0.961905
10    NaN  liblinear            5  0.957143
1     NaN      lbfgs            5  0.957143
4     NaN       saga            5  0.957143
7     NaN        sag            5  0.957143
37    4.0      lbfgs            5  0.957143
49    5.0      lbfgs            5  0.957143
52    5.0       saga            5  0.957143
55    5.0        sag            5  0.957143
58    5.0  liblinear            5  0.957143

In [8]:
voting.named_estimators_

{'TREE': DecisionTreeClassifier(max_depth=5, random_state=26),
 'LR': LogisticRegression(solver='liblinear'),
 'KNN': KNeighborsClassifier(n_neighbors=10)}

In [9]:
dtc=DecisionTreeClassifier(random_state=26)
lr=LogisticRegression()
knn=KNeighborsClassifier()
voting=VotingClassifier([('TREE',dtc),('LR',lr),('KNN',knn)])
voting.fit(X_train,y_train)

y_test1=np.where(y_test=="Malignant",1,0)
y_pred=voting.named_estimators_['TREE'].predict(X_test)
print("Tree acc=",accuracy_score(y_test1,y_pred))
y_pred=voting.named_estimators_['LR'].predict(X_test)
print("Lr acc=",accuracy_score(y_test1,y_pred))
y_pred=voting.named_estimators_['KNN'].predict(X_test)
print("KNN acc=",accuracy_score(y_test1,y_pred))

Tree acc= 0.9476190476190476
Lr acc= 0.9619047619047619
KNN acc= 0.9619047619047619

In [20]:
dtc=DecisionTreeClassifier(random_state=26)
lr=LogisticRegression()
knn=KNeighborsClassifier()
voting=VotingClassifier([('TREE',dtc),('LR',lr),('KNN',knn)],voting='soft',weights=[0.1,10,12])
voting.fit(X_train,y_train)
y_pred=voting.predict(X_test)
accuracy_score(y_test,y_pred)

0.9571428571428572

In [13]:
dtc=DecisionTreeClassifier(random_state=26)
lr=LogisticRegression()
knn=KNeighborsClassifier()
voting=VotingClassifier([('TREE',dtc),('LR',lr),('KNN',knn)])
voting.fit(X_train,y_train)
y_pred=voting.predict(X_test)
accuracy_score(y_test,y_pred)

0.9571428571428572